//DO NOT UPDATE THIS FILE ON GITHUB. DO NOT UPLOAD AN EDITED VERSION OF THIS FILE TO GITHUB. THIS IS TO PROTECT WEBHOOK ID, NETWORK SSID
//AND NETWORK PASSWORD. THIS FILE SHOULD NEED NO CHANGING FOR THE REMAINDER OF THE PROJECT. THANK YOU!

#define SECRET_SSID "AndroidAP"
#define SECRET_PASS "qqnl0996"
#define SECRET_WEBHOOK "/api/webhooks/[id here]"
#define SECRET_TTS "false" //or true
